[workload analyzer]
#queries file 
workload_file=./workload analyzer/workloads/res.wg 
#database schema file
config_file=./workload analyzer/workloads/res.json
#workload features file
output_file=./workload analyzer/workload_features

[knob selector]
#LLM configuration
api_key=sk-ws-H.RXPDHXH.PJIt.MEQCICToZbVDl8fvf_UuUosmehC2w1zIwJSYqnWoOw2Ot1jVAiBZvgsw-d8MXA-6xIdXetGpK1m3uL9L6YdjSXxWXP9Hvw
base_url=https://llm-hemytdofcdo4f00h.cn-beijing.maas.aliyuncs.com/apps/anthropic
model=kimi-k2.6
#candidata knobs file
candidate_knobs=./knob selector/candidate_knobs
#the number of selected parameters
knob_num=20
#database and hardware information 
database_kernel=RDS MySQL 5.7
database_scale=10GB
hardware=8 cores, 16 GB RAM
#selected knobs file
output_file=./knob selector/selected_knobs

[range pruner]
#candidata knobs with detailed description
knob_details=./range pruner/knob_details.json
#LLM configuration
model=kimi-k2.6
#knobs with pruned range
output_file=./range pruner/pruned_knobs

[configuration recommender]
#LLM configuration
model=kimi-k2.6
#tree-search configuration
top_k=2
node_count=3
#memory window size
history_num=5
#inner metrics
metric_file=./configuration recommender/inner_metric
#Performance indicators to be optimized
db_metric=throughput
#LLM_server configuration
LLM_server_IP=127.0.0.1
LLM_server_port=4000
#DB_client configuration
DB_IP=127.0.0.1
DB_IP_Password=123456
#database configuration
DB_User=root
DB_Password=123456
DB_Host=localhost
DB_Name=sbtest
DB_Port=3306
#iteration (number of workload replies)
iteration=100
#benchmarks (TPCC,TPCDS,SYSBENCH,JOB)
benchmark=SYSBENCH

