[workload analyzer]
#queries file 
workload_file=/workspace/AgentTune/benchmark_queries/tpch_all.sql
#database schema file
config_file=/workspace/AgentTune/workload analyzer/workloads/tpch.json
#workload features file
output_file=/workspace/AgentTune/workload analyzer/workload_features_tpch

[knob selector]
#LLM configuration
<<<<<<< HEAD
api_key=sk-SIBEBuEpPbfPHchg1bE693713cD74dC0B8C0C80f5f888d07
base_url=https://aihubmix.com/v1
model=gpt-4o-free
#candidate knobs file
=======
api_key=sk-ws-H.RXPDHXH.PJIt.MEQCICToZbVDl8fvf_UuUosmehC2w1zIwJSYqnWoOw2Ot1jVAiBZvgsw-d8MXA-6xIdXetGpK1m3uL9L6YdjSXxWXP9Hvw
base_url=https://llm-hemytdofcdo4f00h.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
model=qwen3.7-plus
#candidata knobs file
>>>>>>> e25738c028a8ecabb540f79af544ad70c48ac9e8
candidate_knobs=./knob selector/candidate_knobs
#database and hardware info
database_kernel=MySQL 5.7
hardware=64 cores, 246 GB RAM
database_scale=TPC-H 1GB

output_file=./knob selector/selected_knobs

[range pruner]
#candidata knobs with detailed description
knob_details=./range pruner/knob_details.json
#LLM configuration
model=qwen3.7-plus
#knobs with pruned range
output_file=./range pruner/pruned_knobs

[configuration recommender]
#LLM configuration
model=qwen3.7-plus
#tree-search configuration
top_k=2
node_count=3
#memory window size
history_num=5
#inner metrics
metric_file=./configuration recommender/inner_metric
#Performance indicators to be optimized
db_metric=throughput
#LLM_server configuration
LLM_server_IP=127.0.0.1
LLM_server_port=4000
#DB_client configuration
DB_IP=127.0.0.1
DB_IP_Password=123456
#database configuration
DB_User=root
DB_Password=123456
DB_Host=localhost
<<<<<<< HEAD
DB_Name=tpch
=======
DB_Name=sbtest
>>>>>>> e25738c028a8ecabb540f79af544ad70c48ac9e8
DB_Port=3306
#iteration (number of workload replies)
iteration=100
#benchmarks (TPCC,TPCDS,SYSBENCH,JOB)
<<<<<<< HEAD
benchmark=TPCH
benchmark_query_dir=/workspace/AgentTune/benchmark_queries/tpch
=======
benchmark=SYSBENCH

# SQL query directories for JOB / TPCDS benchmarks
job_query_dir=./benchmark_queries/job
tpcds_query_dir=./benchmark_queries/tpcds
>>>>>>> e25738c028a8ecabb540f79af544ad70c48ac9e8
