[workload analyzer]
#queries file（输入）
workload_file=./workload analyzer/workloads/res.wg 
#database schema file（输入）
config_file=./workload analyzer/workloads/res.json
#workload features file（输出）
output_file=./workload analyzer/workload_features

[knob selector]
#LLM 配置
api_key=sk-umo0a8wCjPzSrtQF9763228f09104a2084Fd007d853b66Db
base_url=https://openkey.cloud/v1
model=gpt-4.1
#candidata knobs file
candidate_knobs=./knob selector/candidate_knobs
#the number of selected parameters
knob_num=20
#数据库引擎
database_kernel=MySQL 5.7
# 实验中的数据库规模
database_scale=12GB
# 机器的硬件配置
hardware=CPU:AMD R9-7940H 8 cores 16 threads, **RAM:11GB**
# 将筛选出的旋钮保存到文件
output_file=./knob selector/selected_knobs

[range pruner]
# 所有候选参数的详细描述
knob_details=./range pruner/knob_details.json
# LLM configuration
model=gpt-4.1
# 将裁剪取值范围之后的重要旋钮保存到文件
output_file=./range pruner/pruned_knobs

[configuration recommender]
#LLM configuration gpt-4-0125-preview
model=gpt-4.1
#tree-search configuration
top_k=2
# R size
node_count=3
#memory window size
history_num=5
#inner metrics
metric_file=./configuration recommender/inner_metric
#Performance indicators to be optimized
db_metric=throughput
#LLM_server configuration
LLM_server_IP=127.0.0.1
LLM_server_port=4000
#DB_client configuration
DB_IP=127.0.0.1
# SSH密码
DB_IP_Password=
#database configuration
DB_User=root
# 数据库连接密码为空
DB_Password=123456
# 数据库主机
DB_Host=127.0.0.1
DB_Name=sbtest
# 数据库服务端口
DB_Port=3306
# 迭代次数(在一轮迭代中可能包含多次工作负载重放)
# 实测跑5次迭代要30min
iteration=5
#benchmarks (TPCC,TPCDS,SYSBENCH,JOB)
benchmark=SYSBENCH